khodam_list = [
    "Kecoa Ngebut", "Kadal Kampung", "Saus Tumpah", "Tikus Jatuh", "Bebek Ngibing",
    "Kucing Baper", "Sapi Doyan Sambel", "Singa Kenthir", "Kupu-kupu Keringetan", "Ulat Geli",
    "Ayam Selfie", "Burung Merem", "Gajah Ngompol", "Harimau Pilek", "Kambing Nungging",
    "Panda Ngedrop", "Beruang Gemes", "Tikus Gelembung", "Anjing Keliyengan", "Kucing Terbang",
    "Lumba-lumba Ngupil", "Gajah Gocek", "Kuda Ngedance", "Bebek Berkumis", "Harimau Mainan Skuter",
    "Singa Goyang", "Kelelawar Ngorok", "Burung Pinky", "Hiu Selfie", "Paus Bobo",
    "Kuda Ngakak", "Lumba-lumba Happy", "Kadal Terbang", "Ikan Loncat", "Gajah Gocek",
    "Panda Nge-Mall", "Beruang Terbang", "Tikus Ngebor", "Anjing Jogetan", "Kucing Melompat",
    "Lumba-lumba Ngibing", "Kuda Main Skuter", "Bebek Terbang", "Harimau Ngambek", "Singa Kacamataan",
    "Kelelawar Ngedance", "Burung Mungil", "Hiu Bola", "Paus Ngomel", "Kuda Bobok",
    "Lumba-lumba Obrolan", "Kadal Ngobrol", "Ikan Brewokan", "Gajah Nge-dance", "Panda Kacamataan",
    "Beruang Melambai", "Tikus Ngantuk", "Anjing Melambai", "Kucing Ngorok", "Lumba-lumba Brewokan",
    "Kuda Ngantuk", "Bebek Ngomel", "Harimau Nari", "Singa Bewok", "Kelelawar Kacamataan",
    "Burung Nari", "Hiu Lambaian", "Paus Ngantuk", "Kuda Brewokan", "Lumba-lumba Ngorok",
    "Kadal Kacamataan", "Ikan Ngomel", "Gajah Ngantuk", "Panda Jogetan", "Beruang Kacamataan",
    "Tikus Lambaian", "Anjing Ngantuk", "Kucing Ngomel", "Lumba-lumba Terbang", "Kuda Ngorok",
    "Bebek Ngantuk", "Harimau Kacamataan", "Singa Jogetan", "Kelelawar Ngantuk", "Burung Ngomel",
    "Hiu Jogetan", "Paus Kacamataan", "Kuda Ngantuk", "Lumba-lumba Ngomel", "Kadal Jogetan",
    "Ikan Ngantuk", "Gajah Kacamataan", "Panda Ngantuk", "Beruang Ngomel", "Tikus Kacamataan",
    "Anjing Jogetan", "Kucing Kacamataan", "Lumba-lumba Ngantuk", "Kuda Ngomel", "Bebek Kacamataan",
    "Saus Keju", "Indomie Pedas", "Roti Gosong", "Nasi Uduk Gaul", "Pisang Joget",
    "Sate Ngorok", "Ketoprak Baper", "Tahu Bulat Terbang", "Tempe Melambai", "Bakso Menari",
    "Soto Kenthir", "Rendang Melompat", "Sambal Ngakak", "Bubur Bercanda", "Dumble 5 Kilo",
    "Lemari Terbang", "Panci Nari", "Kasur Ngantuk", "Kursi Melambai", "Meja Kaki Lima",
    "Televisi Ngomel", "Radio Melompat", "Laptop Bobo", "HP Selfie", "Motor Ngebut",
    "Mobil Ngantuk", "Sepeda Ngibing", "Helm Terbang", "Jaket Menari", "Celana Ngakak",
    "Kaos Ngorok", "Tas Gaul", "Sepatu Kacamataan", "Sandal Melambai"
]
